//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Describe061.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Describe061Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDescribe061Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.producer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProducer([NotNull] Describe061Parser.ProducerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeparator([NotNull] Describe061Parser.SeparatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminator([NotNull] Describe061Parser.TerminatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.text_chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText_chunk([NotNull] Describe061Parser.Text_chunkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItem([NotNull] Describe061Parser.ItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] Describe061Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.item_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItem_or_expression([NotNull] Describe061Parser.Item_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.item_or_expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItem_or_expression_list([NotNull] Describe061Parser.Item_or_expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_list([NotNull] Describe061Parser.Expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Describe061Parser.scripture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScripture([NotNull] Describe061Parser.ScriptureContext context);
}
