//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Describe10.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Describe10Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDescribe10Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.producer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProducer([NotNull] Describe10Parser.ProducerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.producer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProducer([NotNull] Describe10Parser.ProducerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.text_chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText_chunk([NotNull] Describe10Parser.Text_chunkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.text_chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText_chunk([NotNull] Describe10Parser.Text_chunkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] Describe10Parser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] Describe10Parser.ItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] Describe10Parser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] Describe10Parser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.item_or_expression_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem_or_expression_part([NotNull] Describe10Parser.Item_or_expression_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.item_or_expression_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem_or_expression_part([NotNull] Describe10Parser.Item_or_expression_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.item_or_expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem_or_expression_list([NotNull] Describe10Parser.Item_or_expression_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.item_or_expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem_or_expression_list([NotNull] Describe10Parser.Item_or_expression_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_list([NotNull] Describe10Parser.Expression_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_list([NotNull] Describe10Parser.Expression_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe10Parser.scripture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScripture([NotNull] Describe10Parser.ScriptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe10Parser.scripture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScripture([NotNull] Describe10Parser.ScriptureContext context);
}
