jQuery(document).ready(function($){var mainHeader=$('header');var scrolling=!1,previousTop=0,currentTop=0,scrollDelta=10,scrollOffset=150;$(window).on('scroll',function(){if(!scrolling){scrolling=!0;(!window.requestAnimationFrame)?setTimeout(autoHideHeader,250):requestAnimationFrame(autoHideHeader)}});function autoHideHeader(){var currentTop=$(window).scrollTop();checkSimpleNavigation(currentTop);previousTop=currentTop;scrolling=!1}
function checkSimpleNavigation(currentTop){if(currentTop>30){mainHeader.addClass('is-scrolling');$('body').addClass('is-scrolling')}else{mainHeader.removeClass('is-scrolling');$('body').removeClass('is-scrolling')}
if(previousTop-currentTop>scrollDelta){mainHeader.removeClass('is-hidden')}else if(currentTop-previousTop>scrollDelta&&currentTop>scrollOffset){mainHeader.addClass('is-hidden')}}});jQuery(document).ready(create_toc);function _e(elm){return document.createElement(elm)}
function _t(elm){return document.createTextNode(elm)}
function create_toc(){let toc=document.querySelector('.toc ul');if(!toc)
return;let content=document.querySelector('.the-content');let h=content.querySelectorAll('h1,h2,h3,h4,h5,h6');h=Array.from(h);var toc_title=_e('LI');toc_title.appendChild(_t('Table of contents'));toc.appendChild(toc_title);toc_title.className='toc-title';toc_title.addEventListener('click',open_toc);for(let i=0;h[i];i++){let id='chapter'+i;h[i].id=id;let li=_e('LI');li.classList.add(h[i].tagName.toLowerCase());let a=_e('A');a.href="#"+id;a.addEventListener('click',function(e){e.preventDefault();smooth_scroll(document.querySelector(this.getAttribute('href')))});let label=h[i].innerHTML.replace("<br>"," – ").replace(/<\/?[^>]+(>|$)/g,"");var escapeMap=[{utf8:'&',html:'&amp;'},{utf8:'<',html:'&lt;'},{utf8:'>',html:'&gt;'},{utf8:"'",html:'&apos;'},{utf8:'"',html:'&quot;'},{utf8:'‘',html:'&lsquo;'},{utf8:'’',html:'&rsquo;'},{utf8:'“',html:'&ldquo;'},{utf8:'”',html:'&rdquo;'}];escapeMap.forEach(element=>{label=label.replace(element.html,element.utf8)});a.appendChild(_t(label));li.appendChild(a);toc.appendChild(li)}}
function open_toc(){let toc=document.querySelector('.toc');if(!toc)
return;toc.classList.toggle('open');if(toc.classList.contains('open'))
toc.style.height=toc.scrollHeight+'px';else toc.style.height=''}
function smooth_scroll(destination_element){let element_bounding=destination_element.getBoundingClientRect(),element_y=element_bounding.top+window.scrollY;jQuery('html, body').animate({scrollTop:element_y-150},500)}
if(document.querySelector('.sharing-social')){for(var i=0,c=document.querySelectorAll('.sharing-social a');c[i];i++){c[i].addEventListener('click',open_social)}}
function open_social(e){e.preventDefault();var w=600,h=400;var screen_width=window.innerWidth?window.innerWidth:document.documentElement.clientWidth?document.documentElement.clientWidth:screen.width;var screen_height=window.innerHeight?window.innerHeight:document.documentElement.clientHeight?document.documentElement.clientHeight:screen.height;var t=(screen_height-h)/2
var l=(screen_width-w)/2
var win=window.open(this.href,"popupWindow","width="+w+", height="+h+", left="+l+", top="+t+", scrollbars=yes");if(window.focus)win.focus()}