//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Describe06.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDescribe06Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Describe06BaseListener : IDescribe06Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.producer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProducer([NotNull] Describe06Parser.ProducerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.producer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProducer([NotNull] Describe06Parser.ProducerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.text_chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText_chunk([NotNull] Describe06Parser.Text_chunkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.text_chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText_chunk([NotNull] Describe06Parser.Text_chunkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem([NotNull] Describe06Parser.ItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem([NotNull] Describe06Parser.ItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] Describe06Parser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] Describe06Parser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.item_or_expression_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem_or_expression_part([NotNull] Describe06Parser.Item_or_expression_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.item_or_expression_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem_or_expression_part([NotNull] Describe06Parser.Item_or_expression_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.item_or_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem_or_expression_list([NotNull] Describe06Parser.Item_or_expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.item_or_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem_or_expression_list([NotNull] Describe06Parser.Item_or_expression_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_list([NotNull] Describe06Parser.Expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_list([NotNull] Describe06Parser.Expression_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Describe06Parser.scripture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScripture([NotNull] Describe06Parser.ScriptureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Describe06Parser.scripture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScripture([NotNull] Describe06Parser.ScriptureContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
